(library
 (name workgraph_upload_api_tests)
 (libraries workgraph core eio_main expect_test_helpers_core)
 (inline_tests)
 (preprocess
  (pps ppx_jane ppx_expect)))

(rule
 (alias runtest)
 (deps socket_test.py ../../examples/history-adapter.py)
 (action
  (run python3 %{dep:socket_test.py} %{exe:../../bin/main.exe})))
