#!/usr/bin/env python3
"""Generate or check per-method references from the executable's actual codecs.

python3 tools/generate_api_reference.py --binary /path/workgraph --output docs/api-reference
Add --check for read-only drift detection. No daemon, network or third-party package.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import xml.sax.saxutils


MANIFEST = 'MANIFEST.json'
NAME = re.compile(r'[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)*\Z')


def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',', ':'))


def sha(data):
    return hashlib.sha256(data).hexdigest()


def cdata(value):
    return '<![CDATA[' + value.replace(']]>', ']]]]><![CDATA[>') + ']]>'


def map_schema_children(schema, transform):
    """Visit schema locations only; examples/default/const remain literal JSON."""
    if not isinstance(schema, dict):
        return schema
    maps = {'properties', 'patternProperties', 'dependentSchemas'}
    singles = {'items', 'additionalProperties', 'unevaluatedProperties', 'unevaluatedItems',
               'contains', 'propertyNames', 'not', 'if', 'then', 'else'}
    lists = {'allOf', 'anyOf', 'oneOf', 'prefixItems'}
    result = {}
    for key, value in sorted(schema.items()):
        if key in maps and isinstance(value, dict):
            result[key] = {name: transform(child) for name, child in sorted(value.items())}
        elif key in singles and isinstance(value, (dict, bool)):
            result[key] = transform(value)
        elif key in lists and isinstance(value, list):
            result[key] = [transform(child) for child in value]
        else:
            result[key] = value
    return result


def compact_schema(schema):
    """Factor exact repeated anonymous subschemas into local Draft 2020-12 $defs.

    Existing reference/base-URI scopes are left untouched. Definitions remain in
    the same document; no external resolver or extra agent file load is needed.
    """
    counts, originals = {}, {}
    scoped = False
    scope_keys = {'$schema', '$id', '$ref', '$anchor', '$dynamicRef', '$dynamicAnchor',
                  '$recursiveRef', '$recursiveAnchor', '$defs', 'definitions'}
    def collect(value):
        nonlocal scoped
        if isinstance(value, dict):
            scoped = scoped or bool(scope_keys.intersection(value))
            key = canonical(value)
            counts[key] = counts.get(key, 0) + 1
            originals[key] = value
        return map_schema_children(value, collect)
    collect(schema)
    if scoped:
        return schema
    repeated = sorted(key for key, count in counts.items() if count > 1 and len(key) >= 384)
    names = {key: 'shape_%03d' % index for index, key in enumerate(repeated, 1)}
    def replace(value):
        name = names.get(canonical(value)) if isinstance(value, dict) else None
        return {'$ref': '#/$defs/' + name} if name else map_schema_children(value, replace)
    result = map_schema_children(schema, replace)
    if names:
        result['$defs'] = {name: map_schema_children(originals[key], replace)
                           for key, name in names.items()}
    return result if len(canonical(result)) < len(canonical(schema)) else schema


def render(catalog):
    if (not isinstance(catalog, dict) or set(catalog) != {'schema_dialect', 'methods'} or
            catalog['schema_dialect'] != 'https://json-schema.org/draft/2020-12/schema' or
            not isinstance(catalog['methods'], list) or not catalog['methods']):
        raise ValueError('expected nonempty executable method catalog')
    files = {}
    rows = []
    methods = catalog['methods']
    names = set()
    for method in methods:
        if (not isinstance(method, dict) or set(method) != {'name', 'mode', 'summary', 'params', 'result'} or
                not isinstance(method['name'], str) or not NAME.fullmatch(method['name']) or
                method['mode'] not in {'read', 'write', 'mutation'} or not isinstance(method['summary'], str) or
                not isinstance(method['params'], dict) or not isinstance(method['result'], dict)):
            raise ValueError('invalid executable method description')
        name = method['name']
        if name == 'index':
            raise ValueError('method name conflicts with the generated index')
        if name in names:
            raise ValueError('duplicate method name: ' + name)
        names.add(name)
        rows.append((name, method['mode'], method['summary']))
        text = '# ' + name + '\n\nGenerated from the executable codecs. Do not edit this file.\n\n'
        text += '```xml\n<workgraph_method name="' + name + '" mode="' + method['mode'] + '">\n'
        text += '<summary>' + cdata(method['summary']) + '</summary>\n'
        for label, key in [('request_schema', 'params'), ('result_schema', 'result')]:
            text += '<' + label + ' dialect="https://json-schema.org/draft/2020-12/schema">\n'
            text += cdata(json.dumps(compact_schema(method[key]), ensure_ascii=False, indent=2)) + '\n'
            text += '</' + label + '>\n'
        text += '</workgraph_method>\n```\n'
        files[name + '.md'] = text.encode()
    intro = '''# Generated API reference

These files come from `workgraph schema`, using the same executable declarations
that validate requests and results. Load one method when needed. For daemon setup,
workflows, retry rules and feature discovery, start with [the agent guide](../../AGENT_GUIDE.md).

Each method file describes its params object and complete result `{data,meta}`.
Repeated schemas use local `$defs` and `$ref` within that same schema block.
Definitions preserve all original fields and validation annotations; no external
file or network lookup is needed. Start at `properties`, then follow needed shapes.
The transport wraps this result in JSON-RPC. `read` has no write effect; `write`
changes state without a durable retry receipt; `mutation` uses a saved retry
identity. Respect each method's more specific contract.

Counters are canonical decimal strings. `x-maxUtf8Bytes`, `x-maximumDecimal` and
other extension annotations describe checks ordinary JSON Schema validators may
ignore. Mapped domain invariants also appear in descriptions; runtime validation
is authoritative. Do not infer permission or operational policy from a schema.

Regenerate with `python3 tools/generate_api_reference.py --binary /absolute/workgraph
--output docs/api-reference`; add `--check` to detect drift without writing files.

| Method | Effect | Purpose |
| --- | --- | --- |
'''
    for name, mode, summary in sorted(rows):
        # Escape table syntax and markup without changing the exact method contract.
        summary = xml.sax.saxutils.escape(summary).replace('|', '&#124;').replace('\n', ' ')
        intro += f'| [{name}]({name}.md) | {mode} | {summary} |\n'
    files['index.md'] = intro.encode()
    manifest = {'generator': 'workgraph-api-reference', 'method_count': len(methods),
                'catalog_sha256': sha(canonical(catalog).encode()),
                'files': {name: sha(data) for name, data in sorted(files.items())}}
    files[MANIFEST] = (json.dumps(manifest, sort_keys=True, indent=2) + '\n').encode()
    return files


def reconcile(directory, files, *, check):
    directory = Path(directory)
    if directory.is_symlink():
        raise ValueError('output directory must not be a symlink')
    existing = set()
    if directory.exists():
        if not directory.is_dir():
            raise ValueError('output must be a directory')
        for path in directory.iterdir():
            if path.is_symlink() or not path.is_file():
                raise ValueError('generated directory must contain only regular files')
            existing.add(path.name)
    if check:
        if existing != set(files):
            raise ValueError('generated file set differs from current executable')
        changed = [name for name, data in files.items() if (directory / name).read_bytes() != data]
        if changed:
            raise ValueError('generated reference drift: ' + ', '.join(sorted(changed)))
        return
    if existing:
        if MANIFEST not in existing:
            raise ValueError('refusing to replace an unmanaged directory')
        previous = json.loads((directory / MANIFEST).read_text())
        owned = previous.get('files') if isinstance(previous, dict) else None
        if (not isinstance(previous, dict) or previous.get('generator') != 'workgraph-api-reference' or not isinstance(owned, dict) or
                set(owned) | {MANIFEST} != existing):
            raise ValueError('generated directory contains unowned files or an invalid manifest')
        for name, digest in owned.items():
            if (directory / name).name != name or sha((directory / name).read_bytes()) != digest:
                raise ValueError('generated file was edited; preserve it before regenerating: ' + name)
    directory.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (directory / name).write_bytes(data)
    for name in existing - set(files):
        (directory / name).unlink()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--binary', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    binary = args.binary.resolve(strict=True)
    catalog = json.loads(subprocess.check_output([str(binary), 'schema'], timeout=30))
    files = render(catalog)
    reconcile(args.output, files, check=args.check)
    print(canonical({'status': 'checked' if args.check else 'generated',
                     'methods': len(catalog['methods']), 'files': len(files)}))


if __name__ == '__main__':
    main()
